Feature/navigation bar
biolab/orange-web2 pull request #13
Opened 2022-12-28 20:14 UTC by teaskvarc

2022-12-28 20:22 UTC, teaskvarc commented
TO DO:
1. Search

2022-12-29 08:50 UTC, mitjapotocin requested changes
I left some comments, otherwise, it looks good 👌 Good job.

I noticed you are not using auto-formatting, or you have a different configuration. Tell me if you need help setting it up, because this need to be formatted correctly before merging.

2022-12-29 08:50 UTC, mitjapotocin commented on components/UiKit/LinkAsButton.tsx
> +const LinkAsButton = styled.a`
This is fine for now, but we will probably change this to a generic button component.
If you want to use the styled.button as a `<a>` tag, you can just use it like this: 
`<Button as="a" href="#">Link with Button styles</Button>`

See documentation: https://styled-components.com/docs/api#as-polymorphic-prop

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/Navbar.tsx
> +              })}
I know I wrote this part, but let's do an implicit return here.

```suggestion
              {config.menu.map(({ name, url }) => (
                <li key={name}>
                  <Link href={url}>{name}</Link>
                </li>
              ))}
```

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/Navbar.tsx
> +const Nav = styled.nav`
This Navbar commponent is looking a bit crowded now.
I recomend moving styled-components into Navbar.styled.tsx (in the same folder)

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/BurgerButton/BurgerButton.tsx
> +          <span className="sr-only">Toggle navigation</span>
Let's stick to styled components, and don't mix class-based styles.
You can created a `styled.span` named SrOnly and put it in UiKit folder.

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/BurgerButton/BurgerButton.tsx
> +function BurgerButton({ onClick }: { onClick: any }){
We know the type of `onClick` 

```suggestion
function BurgerButton({ onClick }: { onClick: () => void }) {
```

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/Navbar.tsx
> +          <MenuWrapper navOpened={navOpened}>
I would suggest using a `$` prefix for styled component props, so you can easily distinguish them from HTML attributes.

```suggestion
          <MenuWrapper $navOpened={navOpened}>
```

2022-12-29 08:50 UTC, mitjapotocin commented on components/Navbar/Navbar.tsx
> +`;
There should be one empty line between every component

2023-01-07 09:38 UTC, mitjapotocin commented on components/Navbar/BurgerButton/BurgerButton.tsx
> +      <SrOnly>Toggle navigation</SrOnly>
@teaskvarc I thik `aria-label` on the burger would be suficient here. We don't need SrOnly

2023-01-08 13:00 UTC, merged